name: test workflow

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: cache
        uses: actions/cache@v3
        with:
          key: x
          path: |
            CVC5/
            bitwuzla/
            bitwuzla-release/
            boolector/
            boolector-release/
            cvc5/
            esbmc/
            mathsat/
            mathsat.tar.gz
            z3/
            z3-4.8.9-x64-ubuntu-16.04.zip
      
      - run: cd .. && ls
      
      
      - name: run action
        uses: ./

