name: test workflow

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Docker Layer Caching2
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: false
      
      - name: run action
        uses: ./

