name: test workflow

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      
      - name: run action
        uses: ./

