name: test workflow

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: run action
        uses: ./
        with:
          temp_option: file.py
          lsverifier_options: -r -f
