name: test workflow

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          key: esbmc-${{ hashFiles('/Dockerfile') }}
          path: |
            /docker-layers
      
      - name: run action
        uses: ./
        with:
          cache-from: type=local,src=/docker-layers
        
      - name: Save Docker layers
        run: docker save -o /docker-layers/image.tar
